# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#hero"
  weight = 10

[[main]]
  name = "Short Courses"
  url = "courses/"
  weight = 20

[[main]]
  name = "Workshops"
  url = "workshops/"
  weight = 30

[[main]]
  name = "Tutorials"
  url = "tutorials/"
  weight = 40

[[main]]
  name = "People"
  url = "authors/"
  weight = 50

[[main]]
  name = "Contact"
  url = "https://rc.virginia.edu/support"
  weight = 60
